name: semantic-odes
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.8.3
  - notebook=7.1.1
  - numpy=1.26.4
  - optuna=3.6.0
  - pandas=2.2.2
  - pip=24.0
  - pysr=0.19.0
  - pytest=8.2.0
  - python=3.12.2
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - lightning=2.2.4
  - scikit-learn=1.4.2
  - scipy=1.12.0
  - seaborn=0.13.2
  - setuptools=69.1.1
  - sympy=1.12
  - tqdm=4.66.4
  - pip:
      - ddeint==0.3.0
      - derivative==0.6.1
      - gurobipy==11.0.3
      - idesolver==1.1.0
      - pysindy==1.7.5
      - torchdiffeq==0.2.4
      - -e .
